CREATE TABLE ESTUDANTE (
id_estudante NUMBER NOT NULL,
nome VARCHAR2(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER (10) UNIQUE NOT NULL,
ativo CHAR (1) NOT NULL,
PRIMARY KEY (id_estudante)
);

-------

CREATE SEQUENCE SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

-------
DROP SEQUENCE seq_estudade;

--- SELECT VEM_SER.SEQ_ESTUDANTE.nextval FROM DUAL;

INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Mateus Castro', TO_DATE('14-09-2001', 'dd-mm-yyyy'), '2021117655', 'S' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Guilherme Rasta', TO_DATE('25-11-2002', 'dd-mm-yyyy'), '2021117666', 'N' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Bernardo Emanoel', TO_DATE('07-03-2003', 'dd-mm-yyyy'), '2021117677', 'S' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Leandra Oliveiraa', TO_DATE('07-11-2001', 'dd-mm-yyyy'), '2021117688', 'S' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Elizangela Animer', TO_DATE('06-05-2003', 'dd-mm-yyyy'), '2021117699', 'N' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Gabriel Jagro', TO_DATE('10-10-2003', 'dd-mm-yyyy'), '2021117700', 'S' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Pedro Henrique', TO_DATE('01-11-1998', 'dd-mm-yyyy'), '2021117710', 'S' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Arthur Kellogz', TO_DATE('04-08-2001', 'dd-mm-yyyy'), '2021117720', 'N' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Gabriel Carraro', TO_DATE('15-03-2000', 'dd-mm-yyyy'), '2021117730', 'S' );
INSERT INTO ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Leonardo Leozin', TO_DATE('20-09-1999', 'dd-mm-yyyy'), '2021117740', 'S' );

--------

SELECT * FROM ESTUDANTE;
